package com.dodsoneng.improvpicker;

//import com.dodsoneng.support.DodsonEng;

import android.content.Context;
import android.provider.Settings;
import android.util.Log;

public class BuildDatabase {
	Context 	_context;
//	DodsonEng de = null;
	private DBAdapter 	_db = null;
	int 		_numOfEntries = 0;
	private static String _tag = Global.TAG + ".BUILDDB";
	
	
	public BuildDatabase (Context context) {
		_context = context;
		_db = new DBAdapter(_context);
//		de = new DodsonEng(mContext, Global.debug_onoff);
	}
	
	/***
     * inserData will insert the questions into the database.
     * Only inserts the questions if they haven't previously 
     * been inserted.
     */
	public void insertData ( )
    {
		Global.logcat(_tag, "insertData()");

		try {
			_db.open();
			_numOfEntries = _db.getNumOfRecords();
			Global.logcat(_tag, "_numOfEntries="+_numOfEntries);

			if (_numOfEntries == 0) {
				insertEmotions (Global.TYPEID_EMOTION);
				insertGenres (Global.TYPEID_GENRE);
				insertCharacters (Global.TYPEID_CHARACTER);
				insertPlaces (Global.TYPEID_PLACE);
				insertEnvironments (Global.TYPEID_ENVIRON);
				insertEvents (Global.TYPEID_EVENT);
				insertAdjectives (Global.TYPEID_ADJECTIVE);
				insertActions (Global.TYPEID_ACTION);
				insertMoments (Global.TYPEID_MOMENT);
			}
			_db.close();
		}
		catch (Exception e) {
			Global.problem(_context, _context.getString(R.string.msgerror1));
			Global.logcat (_tag, e);
		}

    } // End of insertData ()



	private void insertAdjectives (int typeId) {
		_db.insertRecord(1, typeId, 1, "abandoned");
		_db.insertRecord(2, typeId, 1, "lover");
		_db.insertRecord(3, typeId, 1, "benefactor");
		_db.insertRecord(4, typeId, 1, "good");
		_db.insertRecord(5, typeId, 1, "wizard");
		_db.insertRecord(6, typeId, 1, "grimace");
		_db.insertRecord(7, typeId, 1, "catalyst");
		_db.insertRecord(8, typeId, 1, "fancy");
		_db.insertRecord(9, typeId, 1, "compulsive");
		_db.insertRecord(10, typeId, 1, "common");
		_db.insertRecord(11, typeId, 1, "conformist");
		_db.insertRecord(12, typeId, 1, "bold");
		_db.insertRecord(13, typeId, 1, "coward");
		_db.insertRecord(14, typeId, 1, "cult");
		_db.insertRecord(15, typeId, 1, "depressing");
		_db.insertRecord(16, typeId, 1, "challenger");
		_db.insertRecord(17, typeId, 1, "disintegrator");
		_db.insertRecord(18, typeId, 1, "ungracious");
		_db.insertRecord(19, typeId, 1, "drug addict");
		_db.insertRecord(20, typeId, 1, "educated");
		_db.insertRecord(21, typeId, 1, "emotionally ill");
		_db.insertRecord(22, typeId, 1, "entrepreneur");
		_db.insertRecord(23, typeId, 1, "slave");
		_db.insertRecord(24, typeId, 1, "studious");
		_db.insertRecord(25, typeId, 1, "explorer");
		_db.insertRecord(26, typeId, 1, "express");
		_db.insertRecord(27, typeId, 1, "extraordinary");
		_db.insertRecord(28, typeId, 1, "fancy");
		_db.insertRecord(29, typeId, 1, "extrovert");
		_db.insertRecord(30, typeId, 1, "facilitator");
		_db.insertRecord(31, typeId, 1, "fatal");
		_db.insertRecord(32, typeId, 1, "happy");
		_db.insertRecord(33, typeId, 1, "feminist");
		_db.insertRecord(34, typeId, 1, "gossipy");
		_db.insertRecord(35, typeId, 1, "fat");
		_db.insertRecord(36, typeId, 1, "rude");
		_db.insertRecord(37, typeId, 1, "hedonist");
		_db.insertRecord(38, typeId, 1, "hero");
		_db.insertRecord(39, typeId, 1, "hyperactive");
		_db.insertRecord(40, typeId, 1, "idiot");
		_db.insertRecord(41, typeId, 1, "ignorant");
		_db.insertRecord(42, typeId, 1, "impostor");
		_db.insertRecord(43, typeId, 1, "troubled");
		_db.insertRecord(44, typeId, 1, "innocent");
		_db.insertRecord(45, typeId, 1, "intellectual");
		_db.insertRecord(46, typeId, 1, "introvert");
		_db.insertRecord(47, typeId, 1, "investigator");
		_db.insertRecord(48, typeId, 1, "angry");
		_db.insertRecord(49, typeId, 1, "irresponsible");
		_db.insertRecord(50, typeId, 1, "thief");
		_db.insertRecord(51, typeId, 1, "legalist");
		_db.insertRecord(52, typeId, 1, "leader");
		_db.insertRecord(53, typeId, 1, "male chauvinist");
		_db.insertRecord(54, typeId, 1, "skinny");
		_db.insertRecord(55, typeId, 1, "bad");
		_db.insertRecord(56, typeId, 1, "malefactor");
		_db.insertRecord(57, typeId, 1, "manipulator");
		_db.insertRecord(58, typeId, 1, "martyr");
		_db.insertRecord(59, typeId, 1, "masked");
		_db.insertRecord(60, typeId, 1, "masochist");
		_db.insertRecord(61, typeId, 1, "mediator");
		_db.insertRecord(62, typeId, 1, "fearful");
		_db.insertRecord(63, typeId, 1, "mentor");
		_db.insertRecord(64, typeId, 1, "monster");
		_db.insertRecord(65, typeId, 1, "narcissist");
		_db.insertRecord(66, typeId, 1, "observer");
		_db.insertRecord(67, typeId, 1, "peacemaker");
		_db.insertRecord(68, typeId, 1, "penitent");
		_db.insertRecord(69, typeId, 1, "thinker");
		_db.insertRecord(70, typeId, 1, "perfectionist");
		_db.insertRecord(71, typeId, 1, "pessimistic");
		_db.insertRecord(72, typeId, 1, "poor");
		_db.insertRecord(73, typeId, 1, "predator");
		_db.insertRecord(74, typeId, 1, "pretender");
		_db.insertRecord(75, typeId, 1, "private");
		_db.insertRecord(76, typeId, 1, "protector");
		_db.insertRecord(77, typeId, 1, "psycho");
		_db.insertRecord(78, typeId, 1, "psychic");
		_db.insertRecord(79, typeId, 1, "public");
		_db.insertRecord(80, typeId, 1, "rebel");
		_db.insertRecord(81, typeId, 1, "reformer");
		_db.insertRecord(82, typeId, 1, "revolutionary");
		_db.insertRecord(83, typeId, 1, "rich");
		_db.insertRecord(84, typeId, 1, "wise");
		_db.insertRecord(85, typeId, 1, "saboteur");
		_db.insertRecord(86, typeId, 1, "samaritan");
		_db.insertRecord(87, typeId, 1, "seductive");
		_db.insertRecord(88, typeId, 1, "wild");
		_db.insertRecord(89, typeId, 1, "sexy");
		_db.insertRecord(90, typeId, 1, "survivor");
		_db.insertRecord(91, typeId, 1, "lonely");
		_db.insertRecord(92, typeId, 1, "dreamer");
		_db.insertRecord(93, typeId, 1, "subservient");
		_db.insertRecord(94, typeId, 1, "superfeminino");
		_db.insertRecord(95, typeId, 1, "superpowered");
		_db.insertRecord(96, typeId, 1, "perverted");
		_db.insertRecord(97, typeId, 1, "tyrant");
		_db.insertRecord(98, typeId, 1, "betrayed");
		_db.insertRecord(99, typeId, 1, "traitor");
		_db.insertRecord(100, typeId, 1, "transgender");
		_db.insertRecord(101, typeId, 1, "trickster");
		_db.insertRecord(102, typeId, 1, "brave");
		_db.insertRecord(103, typeId, 1, "old");
		_db.insertRecord(104, typeId, 1, "traveler");
		_db.insertRecord(105, typeId, 1, "villain");


		_db.insertRecord(1, typeId, 2, "abandonado");
		_db.insertRecord(2, typeId, 2, "amante");
		_db.insertRecord(3, typeId, 2, "benefactor");
		_db.insertRecord(4, typeId, 2, "bueno");
		_db.insertRecord(5, typeId, 2, "brujo");
		_db.insertRecord(6, typeId, 2, "mueca");
		_db.insertRecord(7, typeId, 2, "catalizador");
		_db.insertRecord(8, typeId, 2, "elegante");
		_db.insertRecord(9, typeId, 2, "compulsivo");
		_db.insertRecord(10, typeId, 2, "común");
		_db.insertRecord(11, typeId, 2, "conformista");
		_db.insertRecord(12, typeId, 2, "audaz");
		_db.insertRecord(13, typeId, 2, "cobarde");
		_db.insertRecord(14, typeId, 2, "culto");
		_db.insertRecord(15, typeId, 2, "deprimente");
		_db.insertRecord(16, typeId, 2, "desafiador");
		_db.insertRecord(17, typeId, 2, "desintegrador");
		_db.insertRecord(18, typeId, 2, "poco gracioso");
		_db.insertRecord(19, typeId, 2, "drogadicto");
		_db.insertRecord(20, typeId, 2, "educado");
		_db.insertRecord(21, typeId, 2, "emocionalmente enferma");
		_db.insertRecord(22, typeId, 2, "emprendedor");
		_db.insertRecord(23, typeId, 2, "esclavo");
		_db.insertRecord(24, typeId, 2, "estudioso");
		_db.insertRecord(25, typeId, 2, "explorador");
		_db.insertRecord(26, typeId, 2, "expresar");
		_db.insertRecord(27, typeId, 2, "extraordinario");
		_db.insertRecord(28, typeId, 2, "fantasía");
		_db.insertRecord(29, typeId, 2, "extrovertido");
		_db.insertRecord(30, typeId, 2, "facilitador");
		_db.insertRecord(31, typeId, 2, "fatal");
		_db.insertRecord(32, typeId, 2, "feliz");
		_db.insertRecord(33, typeId, 2, "feminista");
		_db.insertRecord(34, typeId, 2, "chismosa");
		_db.insertRecord(35, typeId, 2, "grasa");
		_db.insertRecord(36, typeId, 2, "tosco");
		_db.insertRecord(37, typeId, 2, "hedonista");
		_db.insertRecord(38, typeId, 2, "héroe");
		_db.insertRecord(39, typeId, 2, "hiperactivo");
		_db.insertRecord(40, typeId, 2, "idiota");
		_db.insertRecord(41, typeId, 2, "ignorante");
		_db.insertRecord(42, typeId, 2, "impostor");
		_db.insertRecord(43, typeId, 2, "turbulento");
		_db.insertRecord(44, typeId, 2, "inocente");
		_db.insertRecord(45, typeId, 2, "intelectual");
		_db.insertRecord(46, typeId, 2, "introvertido");
		_db.insertRecord(47, typeId, 2, "investigador");
		_db.insertRecord(48, typeId, 2, "iracundo");
		_db.insertRecord(49, typeId, 2, "irresponsable");
		_db.insertRecord(50, typeId, 2, "ladrón");
		_db.insertRecord(51, typeId, 2, "legalista");
		_db.insertRecord(52, typeId, 2, "líder");
		_db.insertRecord(53, typeId, 2, "machista");
		_db.insertRecord(54, typeId, 2, "delgado");
		_db.insertRecord(55, typeId, 2, "apenas");
		_db.insertRecord(56, typeId, 2, "malhechor");
		_db.insertRecord(57, typeId, 2, "manipulador");
		_db.insertRecord(58, typeId, 2, "mártir");
		_db.insertRecord(59, typeId, 2, "enmascarado");
		_db.insertRecord(60, typeId, 2, "masoquista");
		_db.insertRecord(61, typeId, 2, "mediador");
		_db.insertRecord(62, typeId, 2, "temeroso");
		_db.insertRecord(63, typeId, 2, "mentor");
		_db.insertRecord(64, typeId, 2, "monstruo");
		_db.insertRecord(65, typeId, 2, "narcisista");
		_db.insertRecord(66, typeId, 2, "observador");
		_db.insertRecord(67, typeId, 2, "pacificador");
		_db.insertRecord(68, typeId, 2, "penitente");
		_db.insertRecord(69, typeId, 2, "pensador");
		_db.insertRecord(70, typeId, 2, "perfeccionista");
		_db.insertRecord(71, typeId, 2, "pesimista");
		_db.insertRecord(72, typeId, 2, "pobre");
		_db.insertRecord(73, typeId, 2, "depredador");
		_db.insertRecord(74, typeId, 2, "pretendiente");
		_db.insertRecord(75, typeId, 2, "privado");
		_db.insertRecord(76, typeId, 2, "protector");
		_db.insertRecord(77, typeId, 2, "psicópata");
		_db.insertRecord(78, typeId, 2, "psíquico");
		_db.insertRecord(79, typeId, 2, "publico");
		_db.insertRecord(80, typeId, 2, "rebelde");
		_db.insertRecord(81, typeId, 2, "reformador");
		_db.insertRecord(82, typeId, 2, "revolucionario");
		_db.insertRecord(83, typeId, 2, "rico");
		_db.insertRecord(84, typeId, 2, "prudente");
		_db.insertRecord(85, typeId, 2, "saboteador");
		_db.insertRecord(86, typeId, 2, "samaritano");
		_db.insertRecord(87, typeId, 2, "seductor");
		_db.insertRecord(88, typeId, 2, "salvaje");
		_db.insertRecord(89, typeId, 2, "sensual");
		_db.insertRecord(90, typeId, 2, "superviviente");
		_db.insertRecord(91, typeId, 2, "solitario");
		_db.insertRecord(92, typeId, 2, "soñador");
		_db.insertRecord(93, typeId, 2, "subordinado");
		_db.insertRecord(94, typeId, 2, "superfeminino");
		_db.insertRecord(95, typeId, 2, "superpowered");
		_db.insertRecord(96, typeId, 2, "pervertido");
		_db.insertRecord(97, typeId, 2, "tirano");
		_db.insertRecord(98, typeId, 2, "traicionado");
		_db.insertRecord(99, typeId, 2, "traidor");
		_db.insertRecord(100, typeId, 2, "transgénero");
		_db.insertRecord(101, typeId, 2, "tramposo");
		_db.insertRecord(102, typeId, 2, "valiente");
		_db.insertRecord(103, typeId, 2, "viejo");
		_db.insertRecord(104, typeId, 2, "viajero");
		_db.insertRecord(105, typeId, 2, "villano");


		_db.insertRecord(1, typeId, 3, "abandonado");
		_db.insertRecord(2, typeId, 3, "amante");
		_db.insertRecord(3, typeId, 3, "benfeitor");
		_db.insertRecord(4, typeId, 3, "bom");
		_db.insertRecord(5, typeId, 3, "bruxo");
		_db.insertRecord(6, typeId, 3, "careta");
		_db.insertRecord(7, typeId, 3, "catalisador");
		_db.insertRecord(8, typeId, 3, "chique");
		_db.insertRecord(9, typeId, 3, "compulsivo");
		_db.insertRecord(10, typeId, 3, "comum");
		_db.insertRecord(11, typeId, 3, "conformista");
		_db.insertRecord(12, typeId, 3, "corajos");
		_db.insertRecord(13, typeId, 3, "covarde");
		_db.insertRecord(14, typeId, 3, "culto");
		_db.insertRecord(15, typeId, 3, "depressivo");
		_db.insertRecord(16, typeId, 3, "desafiador");
		_db.insertRecord(17, typeId, 3, "desagregador");
		_db.insertRecord(18, typeId, 3, "displicente");
		_db.insertRecord(19, typeId, 3, "drogado");
		_db.insertRecord(20, typeId, 3, "educado");
		_db.insertRecord(21, typeId, 3, "emocionalmente doente");
		_db.insertRecord(22, typeId, 3, "empreendedor");
		_db.insertRecord(23, typeId, 3, "escravo");
		_db.insertRecord(24, typeId, 3, "estudioso");
		_db.insertRecord(25, typeId, 3, "explorador");
		_db.insertRecord(26, typeId, 3, "expresso");
		_db.insertRecord(27, typeId, 3, "extraordinário");
		_db.insertRecord(28, typeId, 3, "extravagante");
		_db.insertRecord(29, typeId, 3, "extrovertido");
		_db.insertRecord(30, typeId, 3, "facilitador");
		_db.insertRecord(31, typeId, 3, "fatal");
		_db.insertRecord(32, typeId, 3, "feliz");
		_db.insertRecord(33, typeId, 3, "feminista");
		_db.insertRecord(34, typeId, 3, "fofoqueiro");
		_db.insertRecord(35, typeId, 3, "gordo");
		_db.insertRecord(36, typeId, 3, "grosseiro");
		_db.insertRecord(37, typeId, 3, "hedonista");
		_db.insertRecord(38, typeId, 3, "herói");
		_db.insertRecord(39, typeId, 3, "hiperativo");
		_db.insertRecord(40, typeId, 3, "idiota");
		_db.insertRecord(41, typeId, 3, "ignorante");
		_db.insertRecord(42, typeId, 3, "impostor");
		_db.insertRecord(43, typeId, 3, "incomodado");
		_db.insertRecord(44, typeId, 3, "inocente");
		_db.insertRecord(45, typeId, 3, "intelectual");
		_db.insertRecord(46, typeId, 3, "introvertido");
		_db.insertRecord(47, typeId, 3, "investigador");
		_db.insertRecord(48, typeId, 3, "irado");
		_db.insertRecord(49, typeId, 3, "irresponsável");
		_db.insertRecord(50, typeId, 3, "ladrao");
		_db.insertRecord(51, typeId, 3, "legalista");
		_db.insertRecord(52, typeId, 3, "líder");
		_db.insertRecord(53, typeId, 3, "machista");
		_db.insertRecord(54, typeId, 3, "magro");
		_db.insertRecord(55, typeId, 3, "mal");
		_db.insertRecord(56, typeId, 3, "malfeitot");
		_db.insertRecord(57, typeId, 3, "manipulador");
		_db.insertRecord(58, typeId, 3, "mártir");
		_db.insertRecord(59, typeId, 3, "mascarado");
		_db.insertRecord(60, typeId, 3, "masoquista");
		_db.insertRecord(61, typeId, 3, "mediador");
		_db.insertRecord(62, typeId, 3, "medroso");
		_db.insertRecord(63, typeId, 3, "mentor");
		_db.insertRecord(64, typeId, 3, "monstro");
		_db.insertRecord(65, typeId, 3, "narcisista");
		_db.insertRecord(66, typeId, 3, "observador");
		_db.insertRecord(67, typeId, 3, "pacificador");
		_db.insertRecord(68, typeId, 3, "penitente");
		_db.insertRecord(69, typeId, 3, "pensador");
		_db.insertRecord(70, typeId, 3, "perfeccionista");
		_db.insertRecord(71, typeId, 3, "pessimista");
		_db.insertRecord(72, typeId, 3, "pobre");
		_db.insertRecord(73, typeId, 3, "predador");
		_db.insertRecord(74, typeId, 3, "pretendente");
		_db.insertRecord(75, typeId, 3, "privado");
		_db.insertRecord(76, typeId, 3, "protetor");
		_db.insertRecord(77, typeId, 3, "psicopata");
		_db.insertRecord(78, typeId, 3, "psíquico");
		_db.insertRecord(79, typeId, 3, "publico");
		_db.insertRecord(80, typeId, 3, "rebelde");
		_db.insertRecord(81, typeId, 3, "reformador");
		_db.insertRecord(82, typeId, 3, "revolucionário");
		_db.insertRecord(83, typeId, 3, "rico");
		_db.insertRecord(84, typeId, 3, "sábio");
		_db.insertRecord(85, typeId, 3, "sabotador");
		_db.insertRecord(86, typeId, 3, "samaritano");
		_db.insertRecord(87, typeId, 3, "sedutor");
		_db.insertRecord(88, typeId, 3, "selvagem");
		_db.insertRecord(89, typeId, 3, "sensual");
		_db.insertRecord(90, typeId, 3, "sobrevivente");
		_db.insertRecord(91, typeId, 3, "solitário");
		_db.insertRecord(92, typeId, 3, "sonhador");
		_db.insertRecord(93, typeId, 3, "subserviente");
		_db.insertRecord(94, typeId, 3, "superfeminino");
		_db.insertRecord(95, typeId, 3, "superpoderoso");
		_db.insertRecord(96, typeId, 3, "tarado");
		_db.insertRecord(97, typeId, 3, "tirano");
		_db.insertRecord(98, typeId, 3, "traido");
		_db.insertRecord(99, typeId, 3, "traidor");
		_db.insertRecord(100, typeId, 3, "transgenero");
		_db.insertRecord(101, typeId, 3, "trapaceiro");
		_db.insertRecord(102, typeId, 3, "valente");
		_db.insertRecord(103, typeId, 3, "velho");
		_db.insertRecord(104, typeId, 3, "viajante");
		_db.insertRecord(105, typeId, 3, "vilão");

	}

	private void insertCharacters (int typeId) {
		_db.insertRecord(1, typeId, 1, "teenager");
		_db.insertRecord(2, typeId, 1, "lawyer");
		_db.insertRecord(3, typeId, 1, "analyst");
		_db.insertRecord(4, typeId, 1, "animal");
		_db.insertRecord(5, typeId, 1, "anti hero");
		_db.insertRecord(6, typeId, 1, "artist");
		_db.insertRecord(7, typeId, 1, "killer");
		_db.insertRecord(8, typeId, 1, "clerk");
		_db.insertRecord(9, typeId, 1, "grandma");
		_db.insertRecord(10, typeId, 1, "grandma");
		_db.insertRecord(11, typeId, 1, "ballet dancer");
		_db.insertRecord(12, typeId, 1, "drunk");
		_db.insertRecord(13, typeId, 1, "bureaucrat");
		_db.insertRecord(14, typeId, 1, "hunter");
		_db.insertRecord(15, typeId, 1, "captain");
		_db.insertRecord(16, typeId, 1, "child");
		_db.insertRecord(17, typeId, 1, "god");
		_db.insertRecord(18, typeId, 1, "goddess");
		_db.insertRecord(19, typeId, 1, "damsel");
		_db.insertRecord(20, typeId, 1, "nurse");
		_db.insertRecord(21, typeId, 1, "hermit");
		_db.insertRecord(22, typeId, 1, "wife");
		_db.insertRecord(23, typeId, 1, "sorcerer");
		_db.insertRecord(24, typeId, 1, "son");
		_db.insertRecord(25, typeId, 1, "nun");
		_db.insertRecord(26, typeId, 1, "general");
		_db.insertRecord(27, typeId, 1, "manager");
		_db.insertRecord(28, typeId, 1, "hero");
		_db.insertRecord(29, typeId, 1, "investigator");
		_db.insertRecord(30, typeId, 1, "player");
		_db.insertRecord(31, typeId, 1, "judge");
		_db.insertRecord(32, typeId, 1, "thief");
		_db.insertRecord(33, typeId, 1, "leader");
		_db.insertRecord(34, typeId, 1, "fighter");
		_db.insertRecord(35, typeId, 1, "mother");
		_db.insertRecord(36, typeId, 1, "magic");
		_db.insertRecord(37, typeId, 1, "husband");
		_db.insertRecord(38, typeId, 1, "doctor");
		_db.insertRecord(39, typeId, 1, "driver");
		_db.insertRecord(40, typeId, 1, "priest");
		_db.insertRecord(41, typeId, 1, "father");
		_db.insertRecord(42, typeId, 1, "clown");
		_db.insertRecord(43, typeId, 1, "boss");
		_db.insertRecord(44, typeId, 1, "fisherman");
		_db.insertRecord(45, typeId, 1, "pilot");
		_db.insertRecord(46, typeId, 1, "poet");
		_db.insertRecord(47, typeId, 1, "cop");
		_db.insertRecord(48, typeId, 1, "teacher");
		_db.insertRecord(49, typeId, 1, "queen");
		_db.insertRecord(50, typeId, 1, "front desk clerk");
		_db.insertRecord(51, typeId, 1, "king");
		_db.insertRecord(52, typeId, 1, "robot");
		_db.insertRecord(53, typeId, 1, "soldier");
		_db.insertRecord(54, typeId, 1, "terrorist");
		_db.insertRecord(55, typeId, 1, "vampire");
		_db.insertRecord(56, typeId, 1, "victim");
		_db.insertRecord(57, typeId, 1, "caretaker");
		_db.insertRecord(58, typeId, 1, "zombie");


		_db.insertRecord(1, typeId, 2, "adolescente");
		_db.insertRecord(2, typeId, 2, "abogado");
		_db.insertRecord(3, typeId, 2, "analista");
		_db.insertRecord(4, typeId, 2, "animal");
		_db.insertRecord(5, typeId, 2, "contra el héroe");
		_db.insertRecord(6, typeId, 2, "artista");
		_db.insertRecord(7, typeId, 2, "asesino");
		_db.insertRecord(8, typeId, 2, "empleado");
		_db.insertRecord(9, typeId, 2, "abuela");
		_db.insertRecord(10, typeId, 2, "abuelo");
		_db.insertRecord(11, typeId, 2, "bailarín");
		_db.insertRecord(12, typeId, 2, "borracho");
		_db.insertRecord(13, typeId, 2, "burócrata");
		_db.insertRecord(14, typeId, 2, "cazador");
		_db.insertRecord(15, typeId, 2, "capitán");
		_db.insertRecord(16, typeId, 2, "niño");
		_db.insertRecord(17, typeId, 2, "dios");
		_db.insertRecord(18, typeId, 2, "diosa");
		_db.insertRecord(19, typeId, 2, "damisela");
		_db.insertRecord(20, typeId, 2, "enfermera");
		_db.insertRecord(21, typeId, 2, "ermitaño");
		_db.insertRecord(22, typeId, 2, "esposa");
		_db.insertRecord(23, typeId, 2, "brujo");
		_db.insertRecord(24, typeId, 2, "hijo");
		_db.insertRecord(25, typeId, 2, "monja");
		_db.insertRecord(26, typeId, 2, "general");
		_db.insertRecord(27, typeId, 2, "gerente");
		_db.insertRecord(28, typeId, 2, "héroe");
		_db.insertRecord(29, typeId, 2, "investigador");
		_db.insertRecord(30, typeId, 2, "jugador");
		_db.insertRecord(31, typeId, 2, "juez");
		_db.insertRecord(32, typeId, 2, "ladrón");
		_db.insertRecord(33, typeId, 2, "lider");
		_db.insertRecord(34, typeId, 2, "combatiente");
		_db.insertRecord(35, typeId, 2, "madre");
		_db.insertRecord(36, typeId, 2, "magia");
		_db.insertRecord(37, typeId, 2, "marido");
		_db.insertRecord(38, typeId, 2, "médico");
		_db.insertRecord(39, typeId, 2, "conductor");
		_db.insertRecord(40, typeId, 2, "sacerdote");
		_db.insertRecord(41, typeId, 2, "padre");
		_db.insertRecord(42, typeId, 2, "payaso");
		_db.insertRecord(43, typeId, 2, "jefe");
		_db.insertRecord(44, typeId, 2, "pescador");
		_db.insertRecord(45, typeId, 2, "piloto");
		_db.insertRecord(46, typeId, 2, "poeta");
		_db.insertRecord(47, typeId, 2, "oficial de policía");
		_db.insertRecord(48, typeId, 2, "profesor");
		_db.insertRecord(49, typeId, 2, "reina");
		_db.insertRecord(50, typeId, 2, "recepcionista");
		_db.insertRecord(51, typeId, 2, "rey");
		_db.insertRecord(52, typeId, 2, "robot");
		_db.insertRecord(53, typeId, 2, "soldado");
		_db.insertRecord(54, typeId, 2, "terrorista");
		_db.insertRecord(55, typeId, 2, "vampiro");
		_db.insertRecord(56, typeId, 2, "víctima");
		_db.insertRecord(57, typeId, 2, "vigilante");
		_db.insertRecord(58, typeId, 2, "zombi");


		_db.insertRecord(1, typeId, 3, "adolescente");
		_db.insertRecord(2, typeId, 3, "advogado");
		_db.insertRecord(3, typeId, 3, "analista");
		_db.insertRecord(4, typeId, 3, "animal");
		_db.insertRecord(5, typeId, 3, "anti herói");
		_db.insertRecord(6, typeId, 3, "artista");
		_db.insertRecord(7, typeId, 3, "assassino");
		_db.insertRecord(8, typeId, 3, "atendente");
		_db.insertRecord(9, typeId, 3, "avó");
		_db.insertRecord(10, typeId, 3, "avô");
		_db.insertRecord(11, typeId, 3, "bailarino");
		_db.insertRecord(12, typeId, 3, "bebado");
		_db.insertRecord(13, typeId, 3, "burocrata");
		_db.insertRecord(14, typeId, 3, "caçador");
		_db.insertRecord(15, typeId, 3, "capitão");
		_db.insertRecord(16, typeId, 3, "criança");
		_db.insertRecord(17, typeId, 3, "deus");
		_db.insertRecord(18, typeId, 3, "deusa");
		_db.insertRecord(19, typeId, 3, "donzela");
		_db.insertRecord(20, typeId, 3, "enfermeiro");
		_db.insertRecord(21, typeId, 3, "eremita");
		_db.insertRecord(22, typeId, 3, "esposa");
		_db.insertRecord(23, typeId, 3, "feiticeiro");
		_db.insertRecord(24, typeId, 3, "filho");
		_db.insertRecord(25, typeId, 3, "freira");
		_db.insertRecord(26, typeId, 3, "general");
		_db.insertRecord(27, typeId, 3, "gerente");
		_db.insertRecord(28, typeId, 3, "herói");
		_db.insertRecord(29, typeId, 3, "investigador");
		_db.insertRecord(30, typeId, 3, "jogador");
		_db.insertRecord(31, typeId, 3, "juiz");
		_db.insertRecord(32, typeId, 3, "ladrão");
		_db.insertRecord(33, typeId, 3, "lider");
		_db.insertRecord(34, typeId, 3, "lutador");
		_db.insertRecord(35, typeId, 3, "mãe");
		_db.insertRecord(36, typeId, 3, "mágico");
		_db.insertRecord(37, typeId, 3, "marido");
		_db.insertRecord(38, typeId, 3, "médico");
		_db.insertRecord(39, typeId, 3, "motorista");
		_db.insertRecord(40, typeId, 3, "padre");
		_db.insertRecord(41, typeId, 3, "pai");
		_db.insertRecord(42, typeId, 3, "palhaço");
		_db.insertRecord(43, typeId, 3, "patrão");
		_db.insertRecord(44, typeId, 3, "pescador");
		_db.insertRecord(45, typeId, 3, "piloto");
		_db.insertRecord(46, typeId, 3, "poeta");
		_db.insertRecord(47, typeId, 3, "policial");
		_db.insertRecord(48, typeId, 3, "professor");
		_db.insertRecord(49, typeId, 3, "rainha");
		_db.insertRecord(50, typeId, 3, "recepcionista");
		_db.insertRecord(51, typeId, 3, "rei");
		_db.insertRecord(52, typeId, 3, "robô");
		_db.insertRecord(53, typeId, 3, "soldado");
		_db.insertRecord(54, typeId, 3, "terrorista");
		_db.insertRecord(55, typeId, 3, "vampiro");
		_db.insertRecord(56, typeId, 3, "vítima");
		_db.insertRecord(57, typeId, 3, "zelador");
		_db.insertRecord(58, typeId, 3, "zumbi");

	}

	private void insertEmotions (int typeId) {
		_db.insertRecord(1, typeId, 1, "affection");
		_db.insertRecord(2, typeId, 1, "affliction");
		_db.insertRecord(3, typeId, 1, "aggressiveness");
		_db.insertRecord(4, typeId, 1, "joy");
		_db.insertRecord(5, typeId, 1, "altruism");
		_db.insertRecord(6, typeId, 1, "ambivalence");
		_db.insertRecord(7, typeId, 1, "friendship");
		_db.insertRecord(8, typeId, 1, "love");
		_db.insertRecord(9, typeId, 1, "anguish");
		_db.insertRecord(10, typeId, 1, "anxiety");
		_db.insertRecord(11, typeId, 1, "anticipation");
		_db.insertRecord(12, typeId, 1, "antipathy");
		_db.insertRecord(13, typeId, 1, "apathy");
		_db.insertRecord(14, typeId, 1, "repentance");
		_db.insertRecord(15, typeId, 1, "arrogance");
		_db.insertRecord(16, typeId, 1, "self-pity");
		_db.insertRecord(17, typeId, 1, "avarice");
		_db.insertRecord(18, typeId, 1, "blessedness");
		_db.insertRecord(19, typeId, 1, "benevolence");
		_db.insertRecord(20, typeId, 1, "goodness");
		_db.insertRecord(21, typeId, 1, "endearment");
		_db.insertRecord(22, typeId, 1, "jealousy");
		_db.insertRecord(23, typeId, 1, "greed");
		_db.insertRecord(24, typeId, 1, "compassion");
		_db.insertRecord(25, typeId, 1, "confusion");
		_db.insertRecord(26, typeId, 1, "embarrassment");
		_db.insertRecord(27, typeId, 1, "contentment");
		_db.insertRecord(28, typeId, 1, "courage");
		_db.insertRecord(29, typeId, 1, "creativity");
		_db.insertRecord(30, typeId, 1, "fault");
		_db.insertRecord(31, typeId, 1, "curiosity");
		_db.insertRecord(32, typeId, 1, "disappointment");
		_db.insertRecord(33, typeId, 1, "depression");
		_db.insertRecord(34, typeId, 1, "outflow");
		_db.insertRecord(35, typeId, 1, "disappointment");
		_db.insertRecord(36, typeId, 1, "dazzle");
		_db.insertRecord(37, typeId, 1, "contempt");
		_db.insertRecord(38, typeId, 1, "doubt");
		_db.insertRecord(39, typeId, 1, "selfishness");
		_db.insertRecord(40, typeId, 1, "empathy");
		_db.insertRecord(41, typeId, 1, "enthusiasm");
		_db.insertRecord(42, typeId, 1, "epiphany");
		_db.insertRecord(43, typeId, 1, "derision");
		_db.insertRecord(44, typeId, 1, "hope");
		_db.insertRecord(45, typeId, 1, "euphoria");
		_db.insertRecord(46, typeId, 1, "excitement");
		_db.insertRecord(47, typeId, 1, "fanaticism");
		_db.insertRecord(48, typeId, 1, "happiness");
		_db.insertRecord(49, typeId, 1, "bleakness");
		_db.insertRecord(50, typeId, 1, "frustration");
		_db.insertRecord(51, typeId, 1, "gratitude");
		_db.insertRecord(52, typeId, 1, "gratification");
		_db.insertRecord(53, typeId, 1, "hysteria");
		_db.insertRecord(54, typeId, 1, "hostility");
		_db.insertRecord(55, typeId, 1, "humility");
		_db.insertRecord(56, typeId, 1, "humiliation");
		_db.insertRecord(57, typeId, 1, "humor");
		_db.insertRecord(58, typeId, 1, "indecision");
		_db.insertRecord(59, typeId, 1, "inspiration");
		_db.insertRecord(60, typeId, 1, "interest");
		_db.insertRecord(61, typeId, 1, "intrigue");
		_db.insertRecord(62, typeId, 1, "envy");
		_db.insertRecord(63, typeId, 1, "will");
		_db.insertRecord(64, typeId, 1, "isolation");
		_db.insertRecord(65, typeId, 1, "lust");
		_db.insertRecord(66, typeId, 1, "hurt");
		_db.insertRecord(67, typeId, 1, "bad mood");
		_db.insertRecord(68, typeId, 1, "illness");
		_db.insertRecord(69, typeId, 1, "fear");
		_db.insertRecord(70, typeId, 1, "melancholy");
		_db.insertRecord(71, typeId, 1, "shucks");
		_db.insertRecord(72, typeId, 1, "nostalgia");
		_db.insertRecord(73, typeId, 1, "hate");
		_db.insertRecord(74, typeId, 1, "proud");
		_db.insertRecord(75, typeId, 1, "patience");
		_db.insertRecord(76, typeId, 1, "passion");
		_db.insertRecord(77, typeId, 1, "panic");
		_db.insertRecord(78, typeId, 1, "peace");
		_db.insertRecord(79, typeId, 1, "feather");
		_db.insertRecord(80, typeId, 1, "pity");
		_db.insertRecord(81, typeId, 1, "possessiveness");
		_db.insertRecord(82, typeId, 1, "pleasure");
		_db.insertRecord(83, typeId, 1, "laziness");
		_db.insertRecord(84, typeId, 1, "concern");
		_db.insertRecord(85, typeId, 1, "rage");
		_db.insertRecord(86, typeId, 1, "remorse");
		_db.insertRecord(87, typeId, 1, "repugnance");
		_db.insertRecord(88, typeId, 1, "resignation");
		_db.insertRecord(89, typeId, 1, "resentment");
		_db.insertRecord(90, typeId, 1, "missing");
		_db.insertRecord(91, typeId, 1, "sympathy");
		_db.insertRecord(92, typeId, 1, "pride");
		_db.insertRecord(93, typeId, 1, "suffering");
		_db.insertRecord(94, typeId, 1, "loneliness");
		_db.insertRecord(95, typeId, 1, "surprise");
		_db.insertRecord(96, typeId, 1, "fright");
		_db.insertRecord(97, typeId, 1, "boredom");
		_db.insertRecord(98, typeId, 1, "timidity");
		_db.insertRecord(99, typeId, 1, "tranquility");
		_db.insertRecord(100, typeId, 1, "sadness");
		_db.insertRecord(101, typeId, 1, "vanity");
		_db.insertRecord(102, typeId, 1, "verity");
		_db.insertRecord(103, typeId, 1, "shame");
		_db.insertRecord(104, typeId, 1, "revenge");


		_db.insertRecord(1, typeId, 2, "afecto");
		_db.insertRecord(2, typeId, 2, "angustia");
		_db.insertRecord(3, typeId, 2, "agresividad");
		_db.insertRecord(4, typeId, 2, "alegría");
		_db.insertRecord(5, typeId, 2, "altruismo");
		_db.insertRecord(6, typeId, 2, "ambivalencia");
		_db.insertRecord(7, typeId, 2, "amistad");
		_db.insertRecord(8, typeId, 2, "amor");
		_db.insertRecord(9, typeId, 2, "angustia");
		_db.insertRecord(10, typeId, 2, "ansiedad");
		_db.insertRecord(11, typeId, 2, "anticipación");
		_db.insertRecord(12, typeId, 2, "antipatía");
		_db.insertRecord(13, typeId, 2, "apatía");
		_db.insertRecord(14, typeId, 2, "arrepentimiento");
		_db.insertRecord(15, typeId, 2, "altivez");
		_db.insertRecord(16, typeId, 2, "lástima de sí mismo");
		_db.insertRecord(17, typeId, 2, "tacañería");
		_db.insertRecord(18, typeId, 2, "bienaventuranza");
		_db.insertRecord(19, typeId, 2, "buena voluntad");
		_db.insertRecord(20, typeId, 2, "bondad");
		_db.insertRecord(21, typeId, 2, "cariño");
		_db.insertRecord(22, typeId, 2, "celos");
		_db.insertRecord(23, typeId, 2, "codicia");
		_db.insertRecord(24, typeId, 2, "compasión");
		_db.insertRecord(25, typeId, 2, "confusión");
		_db.insertRecord(26, typeId, 2, "restricción");
		_db.insertRecord(27, typeId, 2, "alegría");
		_db.insertRecord(28, typeId, 2, "coraje");
		_db.insertRecord(29, typeId, 2, "creatividad");
		_db.insertRecord(30, typeId, 2, "culpa");
		_db.insertRecord(31, typeId, 2, "curiosidad");
		_db.insertRecord(32, typeId, 2, "engaño");
		_db.insertRecord(33, typeId, 2, "depresión");
		_db.insertRecord(34, typeId, 2, "salida");
		_db.insertRecord(35, typeId, 2, "decepción");
		_db.insertRecord(36, typeId, 2, "deslumbrar");
		_db.insertRecord(37, typeId, 2, "desprecio");
		_db.insertRecord(38, typeId, 2, "duda");
		_db.insertRecord(39, typeId, 2, "egoísmo");
		_db.insertRecord(40, typeId, 2, "empatía");
		_db.insertRecord(41, typeId, 2, "entusiasmo");
		_db.insertRecord(42, typeId, 2, "epifanía");
		_db.insertRecord(43, typeId, 2, "burla");
		_db.insertRecord(44, typeId, 2, "esperanza");
		_db.insertRecord(45, typeId, 2, "euforia");
		_db.insertRecord(46, typeId, 2, "emoción");
		_db.insertRecord(47, typeId, 2, "intolerancia");
		_db.insertRecord(48, typeId, 2, "felicidad");
		_db.insertRecord(49, typeId, 2, "desolación");
		_db.insertRecord(50, typeId, 2, "frustración");
		_db.insertRecord(51, typeId, 2, "agradecimiento");
		_db.insertRecord(52, typeId, 2, "gratificación");
		_db.insertRecord(53, typeId, 2, "histeria");
		_db.insertRecord(54, typeId, 2, "hostilidad");
		_db.insertRecord(55, typeId, 2, "humildad");
		_db.insertRecord(56, typeId, 2, "humillación");
		_db.insertRecord(57, typeId, 2, "humor");
		_db.insertRecord(58, typeId, 2, "indecisión");
		_db.insertRecord(59, typeId, 2, "inspiración");
		_db.insertRecord(60, typeId, 2, "interés");
		_db.insertRecord(61, typeId, 2, "intriga");
		_db.insertRecord(62, typeId, 2, "envidia");
		_db.insertRecord(63, typeId, 2, "ira");
		_db.insertRecord(64, typeId, 2, "aislamiento");
		_db.insertRecord(65, typeId, 2, "lujuria");
		_db.insertRecord(66, typeId, 2, "angustia");
		_db.insertRecord(67, typeId, 2, "mal humor");
		_db.insertRecord(68, typeId, 2, "enfermedad");
		_db.insertRecord(69, typeId, 2, "miedo");
		_db.insertRecord(70, typeId, 2, "melancolía");
		_db.insertRecord(71, typeId, 2, "shucks");
		_db.insertRecord(72, typeId, 2, "nostalgia");
		_db.insertRecord(73, typeId, 2, "odio");
		_db.insertRecord(74, typeId, 2, "orgullo");
		_db.insertRecord(75, typeId, 2, "paciencia");
		_db.insertRecord(76, typeId, 2, "pasión");
		_db.insertRecord(77, typeId, 2, "pánico");
		_db.insertRecord(78, typeId, 2, "paz");
		_db.insertRecord(79, typeId, 2, "pluma");
		_db.insertRecord(80, typeId, 2, "lástima");
		_db.insertRecord(81, typeId, 2, "posesividad");
		_db.insertRecord(82, typeId, 2, "placer");
		_db.insertRecord(83, typeId, 2, "pereza");
		_db.insertRecord(84, typeId, 2, "preocupación");
		_db.insertRecord(85, typeId, 2, "ira");
		_db.insertRecord(86, typeId, 2, "compunción");
		_db.insertRecord(87, typeId, 2, "repugnancia");
		_db.insertRecord(88, typeId, 2, "renuncia");
		_db.insertRecord(89, typeId, 2, "resentimiento");
		_db.insertRecord(90, typeId, 2, "que falta");
		_db.insertRecord(91, typeId, 2, "simpatía");
		_db.insertRecord(92, typeId, 2, "orgullo");
		_db.insertRecord(93, typeId, 2, "sufrimiento");
		_db.insertRecord(94, typeId, 2, "soledad");
		_db.insertRecord(95, typeId, 2, "sorpresa");
		_db.insertRecord(96, typeId, 2, "susto");
		_db.insertRecord(97, typeId, 2, "aburrimiento");
		_db.insertRecord(98, typeId, 2, "timidez");
		_db.insertRecord(99, typeId, 2, "tranquilidad");
		_db.insertRecord(100, typeId, 2, "dolor");
		_db.insertRecord(101, typeId, 2, "vanidad");
		_db.insertRecord(102, typeId, 2, "verdad");
		_db.insertRecord(103, typeId, 2, "vergüenza");
		_db.insertRecord(104, typeId, 2, "venganza");


		_db.insertRecord(1, typeId, 3, "afetividade");
		_db.insertRecord(2, typeId, 3, "aflição");
		_db.insertRecord(3, typeId, 3, "agressividade");
		_db.insertRecord(4, typeId, 3, "alegria");
		_db.insertRecord(5, typeId, 3, "altruísmo");
		_db.insertRecord(6, typeId, 3, "ambivalência");
		_db.insertRecord(7, typeId, 3, "amizade");
		_db.insertRecord(8, typeId, 3, "amor");
		_db.insertRecord(9, typeId, 3, "angústia");
		_db.insertRecord(10, typeId, 3, "ansiedade");
		_db.insertRecord(11, typeId, 3, "antecipação");
		_db.insertRecord(12, typeId, 3, "antipatia");
		_db.insertRecord(13, typeId, 3, "apatia");
		_db.insertRecord(14, typeId, 3, "arrependimento");
		_db.insertRecord(15, typeId, 3, "arrogância");
		_db.insertRecord(16, typeId, 3, "auto-piedade");
		_db.insertRecord(17, typeId, 3, "avareza");
		_db.insertRecord(18, typeId, 3, "bem aventurança");
		_db.insertRecord(19, typeId, 3, "benevolência");
		_db.insertRecord(20, typeId, 3, "bondade");
		_db.insertRecord(21, typeId, 3, "carinho");
		_db.insertRecord(22, typeId, 3, "ciúme");
		_db.insertRecord(23, typeId, 3, "cobiça");
		_db.insertRecord(24, typeId, 3, "compaixão");
		_db.insertRecord(25, typeId, 3, "confusão");
		_db.insertRecord(26, typeId, 3, "constrangimento");
		_db.insertRecord(27, typeId, 3, "contentamento");
		_db.insertRecord(28, typeId, 3, "coragem");
		_db.insertRecord(29, typeId, 3, "criatividade");
		_db.insertRecord(30, typeId, 3, "culpa");
		_db.insertRecord(31, typeId, 3, "curiosidade");
		_db.insertRecord(32, typeId, 3, "decepção");
		_db.insertRecord(33, typeId, 3, "depressão");
		_db.insertRecord(34, typeId, 3, "desabafo");
		_db.insertRecord(35, typeId, 3, "desapontamento");
		_db.insertRecord(36, typeId, 3, "deslumbramento");
		_db.insertRecord(37, typeId, 3, "desprezo");
		_db.insertRecord(38, typeId, 3, "dúvida");
		_db.insertRecord(39, typeId, 3, "egoísmo");
		_db.insertRecord(40, typeId, 3, "empatia");
		_db.insertRecord(41, typeId, 3, "entusiasmo");
		_db.insertRecord(42, typeId, 3, "epifania");
		_db.insertRecord(43, typeId, 3, "escarnio");
		_db.insertRecord(44, typeId, 3, "esperança");
		_db.insertRecord(45, typeId, 3, "euforia");
		_db.insertRecord(46, typeId, 3, "excitação");
		_db.insertRecord(47, typeId, 3, "fanatismo");
		_db.insertRecord(48, typeId, 3, "felicidade");
		_db.insertRecord(49, typeId, 3, "frieza");
		_db.insertRecord(50, typeId, 3, "frustração");
		_db.insertRecord(51, typeId, 3, "gratidão");
		_db.insertRecord(52, typeId, 3, "gratificação");
		_db.insertRecord(53, typeId, 3, "histeria");
		_db.insertRecord(54, typeId, 3, "hostilidade");
		_db.insertRecord(55, typeId, 3, "humildade");
		_db.insertRecord(56, typeId, 3, "humilhação");
		_db.insertRecord(57, typeId, 3, "humor");
		_db.insertRecord(58, typeId, 3, "indecisão");
		_db.insertRecord(59, typeId, 3, "inspiração");
		_db.insertRecord(60, typeId, 3, "interesse");
		_db.insertRecord(61, typeId, 3, "intriga");
		_db.insertRecord(62, typeId, 3, "inveja");
		_db.insertRecord(63, typeId, 3, "ira");
		_db.insertRecord(64, typeId, 3, "isolamento");
		_db.insertRecord(65, typeId, 3, "luxúria");
		_db.insertRecord(66, typeId, 3, "mágoa");
		_db.insertRecord(67, typeId, 3, "mau-humor");
		_db.insertRecord(68, typeId, 3, "mazela");
		_db.insertRecord(69, typeId, 3, "medo");
		_db.insertRecord(70, typeId, 3, "melancolia");
		_db.insertRecord(71, typeId, 3, "nojo");
		_db.insertRecord(72, typeId, 3, "nostalgia");
		_db.insertRecord(73, typeId, 3, "Ódio");
		_db.insertRecord(74, typeId, 3, "orgulho");
		_db.insertRecord(75, typeId, 3, "paciência");
		_db.insertRecord(76, typeId, 3, "paixão");
		_db.insertRecord(77, typeId, 3, "pânico");
		_db.insertRecord(78, typeId, 3, "paz");
		_db.insertRecord(79, typeId, 3, "pena");
		_db.insertRecord(80, typeId, 3, "piedade");
		_db.insertRecord(81, typeId, 3, "possessividade");
		_db.insertRecord(82, typeId, 3, "prazer");
		_db.insertRecord(83, typeId, 3, "preguiça");
		_db.insertRecord(84, typeId, 3, "preocupação");
		_db.insertRecord(85, typeId, 3, "raiva");
		_db.insertRecord(86, typeId, 3, "remorso");
		_db.insertRecord(87, typeId, 3, "repugnância");
		_db.insertRecord(88, typeId, 3, "resignação");
		_db.insertRecord(89, typeId, 3, "ressentimento");
		_db.insertRecord(90, typeId, 3, "saudade");
		_db.insertRecord(91, typeId, 3, "simpatia");
		_db.insertRecord(92, typeId, 3, "soberba");
		_db.insertRecord(93, typeId, 3, "sofrimento");
		_db.insertRecord(94, typeId, 3, "solidão");
		_db.insertRecord(95, typeId, 3, "surpresa");
		_db.insertRecord(96, typeId, 3, "susto");
		_db.insertRecord(97, typeId, 3, "tédio");
		_db.insertRecord(98, typeId, 3, "timidez");
		_db.insertRecord(99, typeId, 3, "tranquilidade");
		_db.insertRecord(100, typeId, 3, "tristeza");
		_db.insertRecord(101, typeId, 3, "vaidade");
		_db.insertRecord(102, typeId, 3, "veracidade");
		_db.insertRecord(103, typeId, 3, "vergonha");
		_db.insertRecord(104, typeId, 3, "vingança");

	}
	private void insertEvents (int typeId) {
		_db.insertRecord(1, typeId, 1, "riding car");
		_db.insertRecord(2, typeId, 1, "marriage");
		_db.insertRecord(3, typeId, 1, "gymnastics competition");
		_db.insertRecord(4, typeId, 1, "judo competition");
		_db.insertRecord(5, typeId, 1, "religious worship");
		_db.insertRecord(6, typeId, 1, "birthday party");
		_db.insertRecord(7, typeId, 1, "wedding party");
		_db.insertRecord(8, typeId, 1, "soccer match");
		_db.insertRecord(9, typeId, 1, "dating");
		_db.insertRecord(10, typeId, 1, "lecture");
		_db.insertRecord(11, typeId, 1, "meeting alcoholics anonymous");
		_db.insertRecord(12, typeId, 1, "meeting something anonymous");
		_db.insertRecord(13, typeId, 1, "meeting drug addicts anonymous");
		_db.insertRecord(14, typeId, 1, "meeting of anonymous stalker");
		_db.insertRecord(15, typeId, 1, "traveling by plane");
		_db.insertRecord(16, typeId, 1, "traveling by bus");


		_db.insertRecord(1, typeId, 2, "coche que monta");
		_db.insertRecord(2, typeId, 2, "boda");
		_db.insertRecord(3, typeId, 2, "competencia de gimnasia");
		_db.insertRecord(4, typeId, 2, "la competencia de judo");
		_db.insertRecord(5, typeId, 2, "culto religioso");
		_db.insertRecord(6, typeId, 2, "fiesta de cumpleaños");
		_db.insertRecord(7, typeId, 2, "fiesta de matrimonio");
		_db.insertRecord(8, typeId, 2, "partido de fútbol");
		_db.insertRecord(9, typeId, 2, "citas");
		_db.insertRecord(10, typeId, 2, "conferencia");
		_db.insertRecord(11, typeId, 2, "alcohólicos anónimos de reuniones");
		_db.insertRecord(12, typeId, 2, "encuentro algo anónimo");
		_db.insertRecord(13, typeId, 2, "el cumplimiento de los drogadictos anónimos");
		_db.insertRecord(14, typeId, 2, "reuniones del acosador anónimo");
		_db.insertRecord(15, typeId, 2, "viajar en avión");
		_db.insertRecord(16, typeId, 2, "viaja en autobús");


		_db.insertRecord(1, typeId, 3, "andando de carro");
		_db.insertRecord(2, typeId, 3, "casamento");
		_db.insertRecord(3, typeId, 3, "competição de ginástica");
		_db.insertRecord(4, typeId, 3, "competição de judo");
		_db.insertRecord(5, typeId, 3, "culto religioso");
		_db.insertRecord(6, typeId, 3, "festa de aniversário");
		_db.insertRecord(7, typeId, 3, "festa de casamento");
		_db.insertRecord(8, typeId, 3, "jogo de futebol");
		_db.insertRecord(9, typeId, 3, "namorando");
		_db.insertRecord(10, typeId, 3, "palestra");
		_db.insertRecord(11, typeId, 3, "reunião de alcoólatras anonimos");
		_db.insertRecord(12, typeId, 3, "reunião de alguma coisa anonima");
		_db.insertRecord(13, typeId, 3, "reunião de drogados anonimos");
		_db.insertRecord(14, typeId, 3, "reuniao de tarados anonimos");
		_db.insertRecord(15, typeId, 3, "viajando de avião");
		_db.insertRecord(16, typeId, 3, "viajando de onibus");

	}
	private void insertGenres (int typeId) {
		_db.insertRecord(1, typeId, 1, "action");
		_db.insertRecord(2, typeId, 1, "animation");
		_db.insertRecord(3, typeId, 1, "martial arts");
		_db.insertRecord(4, typeId, 1, "adventure");
		_db.insertRecord(5, typeId, 1, "toys");
		_db.insertRecord(6, typeId, 1, "catastrophe");
		_db.insertRecord(7, typeId, 1, "silent film");
		_db.insertRecord(8, typeId, 1, "comedy");
		_db.insertRecord(9, typeId, 1, "romantic comedy");
		_db.insertRecord(10, typeId, 1, "conspiracy");
		_db.insertRecord(11, typeId, 1, "contemporary");
		_db.insertRecord(12, typeId, 1, "crime");
		_db.insertRecord(13, typeId, 1, "cult");
		_db.insertRecord(14, typeId, 1, "documentary");
		_db.insertRecord(15, typeId, 1, "drama");
		_db.insertRecord(16, typeId, 1, "medical drama");
		_db.insertRecord(17, typeId, 1, "epic");
		_db.insertRecord(18, typeId, 1, "epidemic");
		_db.insertRecord(19, typeId, 1, "scandal");
		_db.insertRecord(20, typeId, 1, "slavery");
		_db.insertRecord(21, typeId, 1, "swashbuckler");
		_db.insertRecord(22, typeId, 1, "espionage");
		_db.insertRecord(23, typeId, 1, "sports");
		_db.insertRecord(24, typeId, 1, "road");
		_db.insertRecord(25, typeId, 1, "extraterrestrial");
		_db.insertRecord(26, typeId, 1, "fable");
		_db.insertRecord(27, typeId, 1, "fantasy");
		_db.insertRecord(28, typeId, 1, "far west");
		_db.insertRecord(29, typeId, 1, "witchcraft");
		_db.insertRecord(30, typeId, 1, "party");
		_db.insertRecord(31, typeId, 1, "science fiction");
		_db.insertRecord(32, typeId, 1, "film noir");
		_db.insertRecord(33, typeId, 1, "franchise / Series");
		_db.insertRecord(34, typeId, 1, "government");
		_db.insertRecord(35, typeId, 1, "war");
		_db.insertRecord(36, typeId, 1, "ghetto");
		_db.insertRecord(37, typeId, 1, "biblical stories");
		_db.insertRecord(38, typeId, 1, "horror");
		_db.insertRecord(39, typeId, 1, "hospital");
		_db.insertRecord(40, typeId, 1, "roman Empire");
		_db.insertRecord(41, typeId, 1, "investigation");
		_db.insertRecord(42, typeId, 1, "jurassic");
		_db.insertRecord(43, typeId, 1, "thief gentleman");
		_db.insertRecord(44, typeId, 1, "book of Memories");
		_db.insertRecord(45, typeId, 1, "machinima");
		_db.insertRecord(46, typeId, 1, "mafia");
		_db.insertRecord(47, typeId, 1, "marvel");
		_db.insertRecord(48, typeId, 1, "masala");
		_db.insertRecord(49, typeId, 1, "melodrama");
		_db.insertRecord(50, typeId, 1, "military");
		_db.insertRecord(51, typeId, 1, "mystery");
		_db.insertRecord(52, typeId, 1, "musical");
		_db.insertRecord(53, typeId, 1, "nelson Rodrigues");
		_db.insertRecord(54, typeId, 1, "paranoia");
		_db.insertRecord(55, typeId, 1, "paranormal");
		_db.insertRecord(56, typeId, 1, "parody");
		_db.insertRecord(57, typeId, 1, "persecution");
		_db.insertRecord(58, typeId, 1, "pirate");
		_db.insertRecord(59, typeId, 1, "cop");
		_db.insertRecord(60, typeId, 1, "policy");
		_db.insertRecord(61, typeId, 1, "pornochanchada");
		_db.insertRecord(62, typeId, 1, "pornographic");
		_db.insertRecord(63, typeId, 1, "prague");
		_db.insertRecord(64, typeId, 1, "prison");
		_db.insertRecord(65, typeId, 1, "cooking show");
		_db.insertRecord(66, typeId, 1, "talk show");
		_db.insertRecord(67, typeId, 1, "advertising");
		_db.insertRecord(68, typeId, 1, "psychopathy");
		_db.insertRecord(69, typeId, 1, "rebellion");
		_db.insertRecord(70, typeId, 1, "religious");
		_db.insertRecord(71, typeId, 1, "romance");
		_db.insertRecord(72, typeId, 1, "saga");
		_db.insertRecord(73, typeId, 1, "satanic");
		_db.insertRecord(74, typeId, 1, "jungle");
		_db.insertRecord(75, typeId, 1, "thriller");
		_db.insertRecord(76, typeId, 1, "telenovela");
		_db.insertRecord(77, typeId, 1, "horror");
		_db.insertRecord(78, typeId, 1, "terrorism");
		_db.insertRecord(79, typeId, 1, "totalitarianism");
		_db.insertRecord(80, typeId, 1, "journalistic transmission");
		_db.insertRecord(81, typeId, 1, "trash");
		_db.insertRecord(82, typeId, 1, "court");
		_db.insertRecord(83, typeId, 1, "alternate universe");
		_db.insertRecord(84, typeId, 1, "urban");
		_db.insertRecord(85, typeId, 1, "vampire");
		_db.insertRecord(86, typeId, 1, "time travel");
		_db.insertRecord(87, typeId, 1, "zombie");


		_db.insertRecord(1, typeId, 2, "acción");
		_db.insertRecord(2, typeId, 2, "animación");
		_db.insertRecord(3, typeId, 2, "artes marciales");
		_db.insertRecord(4, typeId, 2, "aventura");
		_db.insertRecord(5, typeId, 2, "juguetes");
		_db.insertRecord(6, typeId, 2, "catástrofe");
		_db.insertRecord(7, typeId, 2, "cine mudo");
		_db.insertRecord(8, typeId, 2, "comedia");
		_db.insertRecord(9, typeId, 2, "comedia romantica");
		_db.insertRecord(10, typeId, 2, "conspiración");
		_db.insertRecord(11, typeId, 2, "contemporáneo");
		_db.insertRecord(12, typeId, 2, "crimen");
		_db.insertRecord(13, typeId, 2, "culto");
		_db.insertRecord(14, typeId, 2, "documental");
		_db.insertRecord(15, typeId, 2, "drama");
		_db.insertRecord(16, typeId, 2, "drama médico");
		_db.insertRecord(17, typeId, 2, "épico");
		_db.insertRecord(18, typeId, 2, "epidemia");
		_db.insertRecord(19, typeId, 2, "escándalo");
		_db.insertRecord(20, typeId, 2, "esclavitud");
		_db.insertRecord(21, typeId, 2, "bravucón");
		_db.insertRecord(22, typeId, 2, "espionaje");
		_db.insertRecord(23, typeId, 2, "deportes");
		_db.insertRecord(24, typeId, 2, "carretera");
		_db.insertRecord(25, typeId, 2, "poco mundano");
		_db.insertRecord(26, typeId, 2, "fabula");
		_db.insertRecord(27, typeId, 2, "fantasía");
		_db.insertRecord(28, typeId, 2, "wild West");
		_db.insertRecord(29, typeId, 2, "brujería");
		_db.insertRecord(30, typeId, 2, "partido");
		_db.insertRecord(31, typeId, 2, "ciencia ficción");
		_db.insertRecord(32, typeId, 2, "cine negro");
		_db.insertRecord(33, typeId, 2, "franquicias / Series");
		_db.insertRecord(34, typeId, 2, "gobierno");
		_db.insertRecord(35, typeId, 2, "guerra");
		_db.insertRecord(36, typeId, 2, "gueto");
		_db.insertRecord(37, typeId, 2, "historias bíblicas");
		_db.insertRecord(38, typeId, 2, "horror");
		_db.insertRecord(39, typeId, 2, "hospital");
		_db.insertRecord(40, typeId, 2, "imperio Romano");
		_db.insertRecord(41, typeId, 2, "investigación");
		_db.insertRecord(42, typeId, 2, "jurásico");
		_db.insertRecord(43, typeId, 2, "caballero ladrón");
		_db.insertRecord(44, typeId, 2, "memoria");
		_db.insertRecord(45, typeId, 2, "machinima");
		_db.insertRecord(46, typeId, 2, "mafia");
		_db.insertRecord(47, typeId, 2, "maravilla");
		_db.insertRecord(48, typeId, 2, "masala");
		_db.insertRecord(49, typeId, 2, "melodrama");
		_db.insertRecord(50, typeId, 2, "militar");
		_db.insertRecord(51, typeId, 2, "misterio");
		_db.insertRecord(52, typeId, 2, "musical");
		_db.insertRecord(53, typeId, 2, "nelson Rodrigues");
		_db.insertRecord(54, typeId, 2, "paranoia");
		_db.insertRecord(55, typeId, 2, "paranormal");
		_db.insertRecord(56, typeId, 2, "parodia");
		_db.insertRecord(57, typeId, 2, "persecución");
		_db.insertRecord(58, typeId, 2, "pirata");
		_db.insertRecord(59, typeId, 2, "oficial de policía");
		_db.insertRecord(60, typeId, 2, "política");
		_db.insertRecord(61, typeId, 2, "pornochanchada");
		_db.insertRecord(62, typeId, 2, "pornográfico");
		_db.insertRecord(63, typeId, 2, "praga");
		_db.insertRecord(64, typeId, 2, "prisión");
		_db.insertRecord(65, typeId, 2, "programa de cocina");
		_db.insertRecord(66, typeId, 2, "programa de entrevistas");
		_db.insertRecord(67, typeId, 2, "publicidad");
		_db.insertRecord(68, typeId, 2, "psicopatía");
		_db.insertRecord(69, typeId, 2, "rebelión");
		_db.insertRecord(70, typeId, 2, "religioso");
		_db.insertRecord(71, typeId, 2, "novela");
		_db.insertRecord(72, typeId, 2, "saga");
		_db.insertRecord(73, typeId, 2, "satanico");
		_db.insertRecord(74, typeId, 2, "selva");
		_db.insertRecord(75, typeId, 2, "novela de suspense");
		_db.insertRecord(76, typeId, 2, "telenovela");
		_db.insertRecord(77, typeId, 2, "terror");
		_db.insertRecord(78, typeId, 2, "terrorismo");
		_db.insertRecord(79, typeId, 2, "totalitarismo");
		_db.insertRecord(80, typeId, 2, "transmisión periodística");
		_db.insertRecord(81, typeId, 2, "basura");
		_db.insertRecord(82, typeId, 2, "tribunal");
		_db.insertRecord(83, typeId, 2, "universo alternativo");
		_db.insertRecord(84, typeId, 2, "urbano");
		_db.insertRecord(85, typeId, 2, "vampiro");
		_db.insertRecord(86, typeId, 2, "viaje en el tiempo");
		_db.insertRecord(87, typeId, 2, "zombi");


		_db.insertRecord(1, typeId, 3, "ação");
		_db.insertRecord(2, typeId, 3, "animação");
		_db.insertRecord(3, typeId, 3, "artes marciais");
		_db.insertRecord(4, typeId, 3, "aventura");
		_db.insertRecord(5, typeId, 3, "brinquedos");
		_db.insertRecord(6, typeId, 3, "catástrofe");
		_db.insertRecord(7, typeId, 3, "cinema mudo");
		_db.insertRecord(8, typeId, 3, "comédia");
		_db.insertRecord(9, typeId, 3, "comédia romântica");
		_db.insertRecord(10, typeId, 3, "conspiração");
		_db.insertRecord(11, typeId, 3, "contemporâneo");
		_db.insertRecord(12, typeId, 3, "crime");
		_db.insertRecord(13, typeId, 3, "cult");
		_db.insertRecord(14, typeId, 3, "documentário");
		_db.insertRecord(15, typeId, 3, "drama");
		_db.insertRecord(16, typeId, 3, "drama Médico");
		_db.insertRecord(17, typeId, 3, "Épico");
		_db.insertRecord(18, typeId, 3, "epidemia");
		_db.insertRecord(19, typeId, 3, "escandalo");
		_db.insertRecord(20, typeId, 3, "escravidão");
		_db.insertRecord(21, typeId, 3, "espadachim");
		_db.insertRecord(22, typeId, 3, "espionagem");
		_db.insertRecord(23, typeId, 3, "esportes");
		_db.insertRecord(24, typeId, 3, "estrada");
		_db.insertRecord(25, typeId, 3, "extraterrestre");
		_db.insertRecord(26, typeId, 3, "fabula");
		_db.insertRecord(27, typeId, 3, "fantasia");
		_db.insertRecord(28, typeId, 3, "faroeste");
		_db.insertRecord(29, typeId, 3, "feitiçaria");
		_db.insertRecord(30, typeId, 3, "festa");
		_db.insertRecord(31, typeId, 3, "ficção científica");
		_db.insertRecord(32, typeId, 3, "filme noir");
		_db.insertRecord(33, typeId, 3, "franchise/Séries");
		_db.insertRecord(34, typeId, 3, "governo");
		_db.insertRecord(35, typeId, 3, "guerra");
		_db.insertRecord(36, typeId, 3, "gueto");
		_db.insertRecord(37, typeId, 3, "histórias biblicas");
		_db.insertRecord(38, typeId, 3, "horror");
		_db.insertRecord(39, typeId, 3, "hospital");
		_db.insertRecord(40, typeId, 3, "império Romano");
		_db.insertRecord(41, typeId, 3, "investigação");
		_db.insertRecord(42, typeId, 3, "jurássico");
		_db.insertRecord(43, typeId, 3, "ladrão cavalheiro");
		_db.insertRecord(44, typeId, 3, "livro de memórias");
		_db.insertRecord(45, typeId, 3, "machinima");
		_db.insertRecord(46, typeId, 3, "máfia");
		_db.insertRecord(47, typeId, 3, "marvel");
		_db.insertRecord(48, typeId, 3, "masala");
		_db.insertRecord(49, typeId, 3, "melodrama");
		_db.insertRecord(50, typeId, 3, "militar");
		_db.insertRecord(51, typeId, 3, "mistério");
		_db.insertRecord(52, typeId, 3, "musical");
		_db.insertRecord(53, typeId, 3, "nelson Rodrigues");
		_db.insertRecord(54, typeId, 3, "paranóia");
		_db.insertRecord(55, typeId, 3, "paranormal");
		_db.insertRecord(56, typeId, 3, "paródia");
		_db.insertRecord(57, typeId, 3, "perseguição");
		_db.insertRecord(58, typeId, 3, "pirata");
		_db.insertRecord(59, typeId, 3, "policial");
		_db.insertRecord(60, typeId, 3, "política");
		_db.insertRecord(61, typeId, 3, "pornochanchada");
		_db.insertRecord(62, typeId, 3, "pornográfico");
		_db.insertRecord(63, typeId, 3, "praga");
		_db.insertRecord(64, typeId, 3, "prisão");
		_db.insertRecord(65, typeId, 3, "programa de culinária");
		_db.insertRecord(66, typeId, 3, "programa de entrevista");
		_db.insertRecord(67, typeId, 3, "propaganda");
		_db.insertRecord(68, typeId, 3, "psicopatia");
		_db.insertRecord(69, typeId, 3, "rebelião");
		_db.insertRecord(70, typeId, 3, "religioso");
		_db.insertRecord(71, typeId, 3, "romance");
		_db.insertRecord(72, typeId, 3, "saga");
		_db.insertRecord(73, typeId, 3, "satanico");
		_db.insertRecord(74, typeId, 3, "selva");
		_db.insertRecord(75, typeId, 3, "suspense");
		_db.insertRecord(76, typeId, 3, "telenovela");
		_db.insertRecord(77, typeId, 3, "terror ");
		_db.insertRecord(78, typeId, 3, "terrorismo");
		_db.insertRecord(79, typeId, 3, "totalitarismo");
		_db.insertRecord(80, typeId, 3, "transmissão jornalistica ");
		_db.insertRecord(81, typeId, 3, "trash");
		_db.insertRecord(82, typeId, 3, "tribunal");
		_db.insertRecord(83, typeId, 3, "universo alternativo");
		_db.insertRecord(84, typeId, 3, "urbano");
		_db.insertRecord(85, typeId, 3, "vampiro");
		_db.insertRecord(86, typeId, 3, "viagem no tempo");
		_db.insertRecord(87, typeId, 3, "zumbi");

	}
	private void insertPlaces (int typeId) {
		_db.insertRecord(1, typeId, 1, "dance Academy");
		_db.insertRecord(2, typeId, 1, "health club");
		_db.insertRecord(3, typeId, 1, "butchery");
		_db.insertRecord(4, typeId, 1, "airport");
		_db.insertRecord(5, typeId, 1, "post office");
		_db.insertRecord(6, typeId, 1, "competition arena");
		_db.insertRecord(7, typeId, 1, "auditorium");
		_db.insertRecord(8, typeId, 1, "wC");
		_db.insertRecord(9, typeId, 1, "public bathroom");
		_db.insertRecord(10, typeId, 1, "pub");
		_db.insertRecord(11, typeId, 1, "bar");
		_db.insertRecord(12, typeId, 1, "coffee");
		_db.insertRecord(13, typeId, 1, "castle");
		_db.insertRecord(14, typeId, 1, "cemetery");
		_db.insertRecord(15, typeId, 1, "barbecue grill");
		_db.insertRecord(16, typeId, 1, "movie theater");
		_db.insertRecord(17, typeId, 1, "circus");
		_db.insertRecord(18, typeId, 1, "club");
		_db.insertRecord(19, typeId, 1, "school");
		_db.insertRecord(20, typeId, 1, "dentist's office");
		_db.insertRecord(21, typeId, 1, "doctor's office");
		_db.insertRecord(22, typeId, 1, "vet's office");
		_db.insertRecord(23, typeId, 1, "convent");
		_db.insertRecord(24, typeId, 1, "kitchen");
		_db.insertRecord(25, typeId, 1, "police station");
		_db.insertRecord(26, typeId, 1, "desert");
		_db.insertRecord(27, typeId, 1, "discotheque");
		_db.insertRecord(28, typeId, 1, "drive-in");
		_db.insertRecord(29, typeId, 1, "elevator");
		_db.insertRecord(30, typeId, 1, "office");
		_db.insertRecord(31, typeId, 1, "station of Barges");
		_db.insertRecord(32, typeId, 1, "ski Station");
		_db.insertRecord(33, typeId, 1, "metro station");
		_db.insertRecord(34, typeId, 1, "spacial station");
		_db.insertRecord(35, typeId, 1, "parking");
		_db.insertRecord(36, typeId, 1, "stadium");
		_db.insertRecord(37, typeId, 1, "college");
		_db.insertRecord(38, typeId, 1, "market");
		_db.insertRecord(39, typeId, 1, "cinema queue");
		_db.insertRecord(40, typeId, 1, "floriculture");
		_db.insertRecord(41, typeId, 1, "hospital");
		_db.insertRecord(42, typeId, 1, "hotel");
		_db.insertRecord(43, typeId, 1, "church");
		_db.insertRecord(44, typeId, 1, "real estate");
		_db.insertRecord(45, typeId, 1, "garden");
		_db.insertRecord(46, typeId, 1, "jOCKEY");
		_db.insertRecord(47, typeId, 1, "laboratory");
		_db.insertRecord(48, typeId, 1, "lAN house");
		_db.insertRecord(49, typeId, 1, "book store");
		_db.insertRecord(50, typeId, 1, "pet Shop");
		_db.insertRecord(51, typeId, 1, "gun store");
		_db.insertRecord(52, typeId, 1, "goods store for torture");
		_db.insertRecord(53, typeId, 1, "hardware store");
		_db.insertRecord(54, typeId, 1, "utility store");
		_db.insertRecord(55, typeId, 1, "clothing store");
		_db.insertRecord(56, typeId, 1, "wine shop");
		_db.insertRecord(57, typeId, 1, "asylum");
		_db.insertRecord(58, typeId, 1, "museum");
		_db.insertRecord(59, typeId, 1, "spacecraft");
		_db.insertRecord(60, typeId, 1, "morgue");
		_db.insertRecord(61, typeId, 1, "opera");
		_db.insertRecord(62, typeId, 1, "another planet");
		_db.insertRecord(63, typeId, 1, "the bakery");
		_db.insertRecord(64, typeId, 1, "bus stop");
		_db.insertRecord(65, typeId, 1, "amusement park");
		_db.insertRecord(66, typeId, 1, "the school patio");
		_db.insertRecord(67, typeId, 1, "pyramid");
		_db.insertRecord(68, typeId, 1, "north Pole");
		_db.insertRecord(69, typeId, 1, "basement");
		_db.insertRecord(70, typeId, 1, "concierge of the building");
		_db.insertRecord(71, typeId, 1, "port");
		_db.insertRecord(72, typeId, 1, "gas station");
		_db.insertRecord(73, typeId, 1, "square");
		_db.insertRecord(74, typeId, 1, "beach");
		_db.insertRecord(75, typeId, 1, "prison");
		_db.insertRecord(76, typeId, 1, "bedroom");
		_db.insertRecord(77, typeId, 1, "backyard");
		_db.insertRecord(78, typeId, 1, "reception");
		_db.insertRecord(79, typeId, 1, "restaurant");
		_db.insertRecord(80, typeId, 1, "bus station");
		_db.insertRecord(81, typeId, 1, "street");
		_db.insertRecord(82, typeId, 1, "principal's office");
		_db.insertRecord(83, typeId, 1, "classroom");
		_db.insertRecord(84, typeId, 1, "living room");
		_db.insertRecord(85, typeId, 1, "interrogation room");
		_db.insertRecord(86, typeId, 1, "dining room");
		_db.insertRecord(87, typeId, 1, "beauty salon");
		_db.insertRecord(88, typeId, 1, "sambodromo");
		_db.insertRecord(89, typeId, 1, "jungle");
		_db.insertRecord(90, typeId, 1, "sexshop");
		_db.insertRecord(91, typeId, 1, "shooping center");
		_db.insertRecord(92, typeId, 1, "ice cream shop");
		_db.insertRecord(93, typeId, 1, "attic");
		_db.insertRecord(94, typeId, 1, "supermarket");
		_db.insertRecord(95, typeId, 1, "theater");
		_db.insertRecord(96, typeId, 1, "court");
		_db.insertRecord(97, typeId, 1, "tomb");


		_db.insertRecord(1, typeId, 2, "academia de baile");
		_db.insertRecord(2, typeId, 2, "gimnasio");
		_db.insertRecord(3, typeId, 2, "carnicería");
		_db.insertRecord(4, typeId, 2, "aeropuerto");
		_db.insertRecord(5, typeId, 2, "correos");
		_db.insertRecord(6, typeId, 2, "pista de competición");
		_db.insertRecord(7, typeId, 2, "sala");
		_db.insertRecord(8, typeId, 2, "cuarto de baño");
		_db.insertRecord(9, typeId, 2, "baño publico");
		_db.insertRecord(10, typeId, 2, "bar");
		_db.insertRecord(11, typeId, 2, "boteco");
		_db.insertRecord(12, typeId, 2, "café");
		_db.insertRecord(13, typeId, 2, "castillo");
		_db.insertRecord(14, typeId, 2, "cementerio");
		_db.insertRecord(15, typeId, 2, "barbacoa");
		_db.insertRecord(16, typeId, 2, "cine");
		_db.insertRecord(17, typeId, 2, "circo");
		_db.insertRecord(18, typeId, 2, "club");
		_db.insertRecord(19, typeId, 2, "colegio");
		_db.insertRecord(20, typeId, 2, "dental");
		_db.insertRecord(21, typeId, 2, "consultorio médico");
		_db.insertRecord(22, typeId, 2, "oficina veterinaria");
		_db.insertRecord(23, typeId, 2, "convento");
		_db.insertRecord(24, typeId, 2, "cocina");
		_db.insertRecord(25, typeId, 2, "estación");
		_db.insertRecord(26, typeId, 2, "desierto");
		_db.insertRecord(27, typeId, 2, "discoteca");
		_db.insertRecord(28, typeId, 2, "drivein");
		_db.insertRecord(29, typeId, 2, "ascensor");
		_db.insertRecord(30, typeId, 2, "oficina");
		_db.insertRecord(31, typeId, 2, "estación de barcazas");
		_db.insertRecord(32, typeId, 2, "estación de esquí");
		_db.insertRecord(33, typeId, 2, "estación del metro");
		_db.insertRecord(34, typeId, 2, "estación espacial");
		_db.insertRecord(35, typeId, 2, "aparcamiento");
		_db.insertRecord(36, typeId, 2, "estadio");
		_db.insertRecord(37, typeId, 2, "colegio");
		_db.insertRecord(38, typeId, 2, "feria");
		_db.insertRecord(39, typeId, 2, "cola de cine");
		_db.insertRecord(40, typeId, 2, "floricultura");
		_db.insertRecord(41, typeId, 2, "hospital");
		_db.insertRecord(42, typeId, 2, "hotel");
		_db.insertRecord(43, typeId, 2, "iglesia");
		_db.insertRecord(44, typeId, 2, "bienes raíces");
		_db.insertRecord(45, typeId, 2, "jardín");
		_db.insertRecord(46, typeId, 2, "jOCKEY");
		_db.insertRecord(47, typeId, 2, "laboratorio");
		_db.insertRecord(48, typeId, 2, "café Internet");
		_db.insertRecord(49, typeId, 2, "librería");
		_db.insertRecord(50, typeId, 2, "tienda de animales");
		_db.insertRecord(51, typeId, 2, "tienda de armas");
		_db.insertRecord(52, typeId, 2, "tienda de artículos para la tortura");
		_db.insertRecord(53, typeId, 2, "droguería");
		_db.insertRecord(54, typeId, 2, "droguería");
		_db.insertRecord(55, typeId, 2, "tienda de ropa");
		_db.insertRecord(56, typeId, 2, "bodega");
		_db.insertRecord(57, typeId, 2, "bughouse");
		_db.insertRecord(58, typeId, 2, "museo");
		_db.insertRecord(59, typeId, 2, "nave espacial");
		_db.insertRecord(60, typeId, 2, "morgue");
		_db.insertRecord(61, typeId, 2, "ópera");
		_db.insertRecord(62, typeId, 2, "otro planeta");
		_db.insertRecord(63, typeId, 2, "panadería");
		_db.insertRecord(64, typeId, 2, "parada de autobus");
		_db.insertRecord(65, typeId, 2, "parque de diversiones");
		_db.insertRecord(66, typeId, 2, "el patio de la escuela");
		_db.insertRecord(67, typeId, 2, "pirámide");
		_db.insertRecord(68, typeId, 2, "polo Norte");
		_db.insertRecord(69, typeId, 2, "sótano");
		_db.insertRecord(70, typeId, 2, "conserje de la finca");
		_db.insertRecord(71, typeId, 2, "puerto");
		_db.insertRecord(72, typeId, 2, "gasolinera");
		_db.insertRecord(73, typeId, 2, "plaza");
		_db.insertRecord(74, typeId, 2, "playa");
		_db.insertRecord(75, typeId, 2, "prisión");
		_db.insertRecord(76, typeId, 2, "habitación");
		_db.insertRecord(77, typeId, 2, "patio trasero");
		_db.insertRecord(78, typeId, 2, "recepción");
		_db.insertRecord(79, typeId, 2, "restaurante");
		_db.insertRecord(80, typeId, 2, "estación de autobús");
		_db.insertRecord(81, typeId, 2, "calle");
		_db.insertRecord(82, typeId, 2, "director de la sala");
		_db.insertRecord(83, typeId, 2, "aula");
		_db.insertRecord(84, typeId, 2, "sala de estar");
		_db.insertRecord(85, typeId, 2, "sala de interrogatorios");
		_db.insertRecord(86, typeId, 2, "comedor");
		_db.insertRecord(87, typeId, 2, "salón de belleza");
		_db.insertRecord(88, typeId, 2, "sambódromo");
		_db.insertRecord(89, typeId, 2, "selva");
		_db.insertRecord(90, typeId, 2, "sexshop");
		_db.insertRecord(91, typeId, 2, "centro de shooping");
		_db.insertRecord(92, typeId, 2, "heladería");
		_db.insertRecord(93, typeId, 2, "ático");
		_db.insertRecord(94, typeId, 2, "supermercado");
		_db.insertRecord(95, typeId, 2, "teatro");
		_db.insertRecord(96, typeId, 2, "tribunal");
		_db.insertRecord(97, typeId, 2, "tumba");


		_db.insertRecord(1, typeId, 3, "academia de dança");
		_db.insertRecord(2, typeId, 3, "academia de ginástica");
		_db.insertRecord(3, typeId, 3, "açougue");
		_db.insertRecord(4, typeId, 3, "aeroporto");
		_db.insertRecord(5, typeId, 3, "agência de correio");
		_db.insertRecord(6, typeId, 3, "arena de competição");
		_db.insertRecord(7, typeId, 3, "auditório");
		_db.insertRecord(8, typeId, 3, "banheiro");
		_db.insertRecord(9, typeId, 3, "banheiro publico");
		_db.insertRecord(10, typeId, 3, "bar");
		_db.insertRecord(11, typeId, 3, "boteco");
		_db.insertRecord(12, typeId, 3, "café");
		_db.insertRecord(13, typeId, 3, "castelo");
		_db.insertRecord(14, typeId, 3, "cemitério");
		_db.insertRecord(15, typeId, 3, "churrasqueira");
		_db.insertRecord(16, typeId, 3, "cinema");
		_db.insertRecord(17, typeId, 3, "circo");
		_db.insertRecord(18, typeId, 3, "clube");
		_db.insertRecord(19, typeId, 3, "colégio");
		_db.insertRecord(20, typeId, 3, "consultório dentário");
		_db.insertRecord(21, typeId, 3, "consultório médico");
		_db.insertRecord(22, typeId, 3, "consultório veterinário");
		_db.insertRecord(23, typeId, 3, "convento");
		_db.insertRecord(24, typeId, 3, "cozinha");
		_db.insertRecord(25, typeId, 3, "delegacia");
		_db.insertRecord(26, typeId, 3, "deserto");
		_db.insertRecord(27, typeId, 3, "discoteca");
		_db.insertRecord(28, typeId, 3, "drivein");
		_db.insertRecord(29, typeId, 3, "elevador");
		_db.insertRecord(30, typeId, 3, "escritório");
		_db.insertRecord(31, typeId, 3, "estação das barcas");
		_db.insertRecord(32, typeId, 3, "estação de esqui");
		_db.insertRecord(33, typeId, 3, "estação do metrô");
		_db.insertRecord(34, typeId, 3, "estação espacial");
		_db.insertRecord(35, typeId, 3, "estacionamento");
		_db.insertRecord(36, typeId, 3, "estádio");
		_db.insertRecord(37, typeId, 3, "faculdade");
		_db.insertRecord(38, typeId, 3, "feira");
		_db.insertRecord(39, typeId, 3, "fila do cinema");
		_db.insertRecord(40, typeId, 3, "floricultura");
		_db.insertRecord(41, typeId, 3, "hospital");
		_db.insertRecord(42, typeId, 3, "hotel");
		_db.insertRecord(43, typeId, 3, "igreja");
		_db.insertRecord(44, typeId, 3, "imobiliária");
		_db.insertRecord(45, typeId, 3, "jardim");
		_db.insertRecord(46, typeId, 3, "jóckey");
		_db.insertRecord(47, typeId, 3, "laboratório");
		_db.insertRecord(48, typeId, 3, "lan house");
		_db.insertRecord(49, typeId, 3, "livraria");
		_db.insertRecord(50, typeId, 3, "loja de animais");
		_db.insertRecord(51, typeId, 3, "loja de armas");
		_db.insertRecord(52, typeId, 3, "loja de artigos para tortura");
		_db.insertRecord(53, typeId, 3, "loja de ferragens");
		_db.insertRecord(54, typeId, 3, "loja de ferramentas");
		_db.insertRecord(55, typeId, 3, "loja de roupas");
		_db.insertRecord(56, typeId, 3, "loja de vinhos");
		_db.insertRecord(57, typeId, 3, "manicômio");
		_db.insertRecord(58, typeId, 3, "museu");
		_db.insertRecord(59, typeId, 3, "nave espacial");
		_db.insertRecord(60, typeId, 3, "necrotério");
		_db.insertRecord(61, typeId, 3, "ópera");
		_db.insertRecord(62, typeId, 3, "outro planeta");
		_db.insertRecord(63, typeId, 3, "padaria");
		_db.insertRecord(64, typeId, 3, "parada de onibus");
		_db.insertRecord(65, typeId, 3, "parque de diversões");
		_db.insertRecord(66, typeId, 3, "patio do colégio");
		_db.insertRecord(67, typeId, 3, "pirâmide");
		_db.insertRecord(68, typeId, 3, "polo norte");
		_db.insertRecord(69, typeId, 3, "porão");
		_db.insertRecord(70, typeId, 3, "portaria do prédio");
		_db.insertRecord(71, typeId, 3, "porto");
		_db.insertRecord(72, typeId, 3, "posto de gasolina");
		_db.insertRecord(73, typeId, 3, "praça");
		_db.insertRecord(74, typeId, 3, "praia");
		_db.insertRecord(75, typeId, 3, "prisão");
		_db.insertRecord(76, typeId, 3, "quarto");
		_db.insertRecord(77, typeId, 3, "quintal");
		_db.insertRecord(78, typeId, 3, "recepção");
		_db.insertRecord(79, typeId, 3, "restaurante");
		_db.insertRecord(80, typeId, 3, "rodoviária");
		_db.insertRecord(81, typeId, 3, "rua");
		_db.insertRecord(82, typeId, 3, "sala da diretora");
		_db.insertRecord(83, typeId, 3, "sala de aula");
		_db.insertRecord(84, typeId, 3, "sala de estar");
		_db.insertRecord(85, typeId, 3, "sala de interrogatório");
		_db.insertRecord(86, typeId, 3, "sala de jantar");
		_db.insertRecord(87, typeId, 3, "salão de beleza");
		_db.insertRecord(88, typeId, 3, "sambodromo");
		_db.insertRecord(89, typeId, 3, "selva");
		_db.insertRecord(90, typeId, 3, "sexshop");
		_db.insertRecord(91, typeId, 3, "shooping center");
		_db.insertRecord(92, typeId, 3, "sorveteria");
		_db.insertRecord(93, typeId, 3, "sótão");
		_db.insertRecord(94, typeId, 3, "supermercado");
		_db.insertRecord(95, typeId, 3, "teatro");
		_db.insertRecord(96, typeId, 3, "tribunal");
		_db.insertRecord(97, typeId, 3, "tumba");

	}

	private void insertEnvironments (int typeId) {


	}
	private void insertActions (int typeId) {


	}
	private void insertMoments (int typeId) {


	}

}
